import React from 'react';
import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import ModalProvider from '@/contexts/modal-context';
import { cn } from '@/lib/utils';
import Header from '@/components/header';
import { Toaster } from '@/components/ui/sonner';
import './globals.css';

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = function ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased w-full',
          fontSans.variable
        )}
      >
        <ModalProvider>
          <Header />
          {children}
          <Toaster richColors theme="light" position="top-center" />
        </ModalProvider>
      </body>
    </html>
  );
};

export default RootLayout;
